spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eokten/owu-config-service
          default-label: main
          search-paths: config
          clone-on-start: true
    bus:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, bus-refresh

server:
  port: 8888